serviceAccount: 'projects/ml-framework-config/serviceAccounts/build-create-git-projects'
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: 'call-cloud-functions'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  entrypoint: 'bash'
  args:
    - -c
    - |
      git clone https://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@github.com/aquilesIIIMB/data-science-projects-creation.git
      ls -la
      gsutil cp -r data-science-projects-creation gs://bucket-create-git-projects-service-accounts

