serviceAccount: 'projects/ml-framework-config/serviceAccounts/build-create-git-projects'
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: 'call-cloud-functions'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - call
  - create-git-projects-service-accounts
  - --region=us-central1
  - --account=build-create-git-projects@ml-framework-config.iam.gserviceaccount.com
