serviceAccount: 'projects/ml-framework-config/serviceAccounts/build-create-git-projects'
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: 'call-cloud-functions'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - pubsub
  - topics
  - topic-create-git-projects-service-accounts
  - --region=us-central1
  - --message="Hello World!"
